authorName: lycaoduong
experimentName: fcg-former
trialConcurrency: 1
maxExecDuration: 99999d
maxTrialNum: 4
trainingServicePlatform: local
searchSpacePath: D:/lycaoduong/workspace/src_code/github_repo/oblabs/Funcs_Group_CLS/configs/nni/search_space.json
logDir: D:/lycaoduong/workspace/src_code/github_repo/oblabs/runs/nni_logs
useAnnotation: false
localConfig:
  useActiveGpu: true
tuner:
  builtinTunerName: GridSearch
trial:
  codeDir: D:/lycaoduong/workspace/src_code/github_repo/oblabs/Funcs_Group_CLS
  command: python train.py #--request-from-nni
  gpuNum: 0